# Generated by Django 4.2.1 on 2023-05-31 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="checked",
        ),
    ]
