# Generated by Django 4.2.1 on 2023-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_task_description_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.TextField(max_length=255),
        ),
    ]
