# Generated by Django 4.2.1 on 2023-06-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_tag_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1: Low"), (2, "2: Normal"), (3, "3: High")],
                default="2: Normal",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="tasks.tag"
            ),
        ),
    ]
